### PR TITLE
Switch to github actions

### PR DESCRIPTION
**Pull request by freddyheppell**
Travis has changed their billing policy so open source CI is no longer totally free, and this is causing the library's CI to fail. Now the new version that fixes 5 division has been released I've deprecated my fork, but I thought it'd be helpful to PR my switch to GitHub Actions.

Currently it only runs on ubuntu-latest on nodes 10, 12, 14, 15 and 16, whereas the Travis action also ran on windows and macOS. Personally I thought it was slightly overkill to test on other OSes when the library has no native interaction, but I'd be happy to edit this PR to test on windows and macOS too.

### CODE REVIEW

**Comment by Prabhakar-Poudel** [comment]
@freddyheppell Do you think this PR is still useful?
I'd be happy to merge it, if we can verify it still works as expected.

**Comment by freddyheppell** [comment]
Yes I believe so as Travis still doesn't offer open source CI any more, so currently this library doesn't have CI.

**Review by Prabhakar-Poudel — APPROVED** [review]

**Comment by Prabhakar-Poudel** [comment]
Thanks, @freddyheppell.

**Comment by Prabhakar-Poudel** [comment]
https://github.com/Prabhakar-Poudel/random-prime/runs/4574300343?check_suite_focus=true
let's do it in yarn?

**Comment by freddyheppell** [comment]
@Prabhakar-Poudel ah yep I forgot I switched to just NPM in my fork. The setup-node action already installs yarn so it should just be a case of changing `npm ci` to the yarn equivalent `yarn install --frozen-lockfile` and then change the run commands.

**Pull request merged**
